#define OFFSETS_H
#include <windows.h>

#define OFFSET_GAME_MANAGER 0x51E27C8
#define OFFSET_GAME_MANAGER_ENTITY_COUNT 0x1D8
#define OFFSET_GAME_MANAGER_ENTITY_LIST 0x1C8

#define OFFSET_GAME_RENDERER 0x51E2680
#define OFFSET_GAME_RENDERER_DEREF 0x0

#define OFFSET_ENTITY_COMPONENT 0x28
#define OFFSET_ENTITY_COMPONENT_LIST 0x1C8
#define OFFSET_ENTITY_COMPONENT_HEALTH 0x140

#define OFFSET_STATUS_MANAGER 0x51E2768
#define OFFSET_STATUS_MANAGER_CONTAINER  0x68
#define OFFSET_STATUS_MANAGER_LOCALENTITY 0x28

#define ENTITY_MARKER_VT_OFFSET  0x37AC120
#define ENTITY_MARKER_ENABLED_OFFSET 0x530

#define OFFSET_ENTITY_REPLICATION 0xA8
#define OFFSET_ENTITY_REPLICATION_TEAM 0x19E 
#define OFFSET_ENTITY_REPLICATION_NAME 0x1C8

#define OFFSET_CAMERA_MANAGER 0x504DC18 
#define OFFSET_CAMERA_ENGINELINK 0xE0
#define OFFSET_CAMERA_ENGINE 0x1C8
#define OFFSET_CAMERA_ENGINE_CAMERA 0x08

#define OFFSET_CAMERA_RIGHT 0xD0 
#define OFFSET_CAMERA_UP 0xE0 
#define OFFSET_CAMERA_FORWARD 0xF0 
#define OFFSET_CAMERA_TRANSLATION 0x100
#define OFFSET_CAMERA_FOVX 0x110 
#define OFFSET_CAMERA_FOVY 0x124 

inline bool _VALID(UINT_PTR Ptr)
{
	return (Ptr >= 0x10000) && (Ptr < 0xFFE00000);
}